# Generated by Django 5.0.1 on 2024-01-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productcategory_remove_basket_items_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
    ]
